name: RealisticGrenades
main: me.tedwoodworth.grenades.RealisticGrenades
version: 0.1.0
description: This plugin adds realistic grenades into the game.
author: Tedsworth

api-version: 1.17
depend: [ ]